name: PHP Lint & Codeception
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php: [ '7.4', '8.0', '8.1' ]
    
    name: PHP ${{ matrix.php }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup PHP
      uses: nanasess/setup-php@master
      with:
        php-version: ${{ matrix.php }}
    
    - name: Start MySQL and create database
      run: |
        sudo systemctl start mysql.service
        sudo mysql -uroot -proot -e "CREATE DATABASE simplecms CHARSET utf8mb4 COLLATE utf8mb4_unicode_ci"
    - name: PHP Lint
      run: if find . -name "*.php" ! -path "./vendor/*" -print0 | xargs -0 -n 1 -P 8 php -l | grep -v "No syntax errors detected"; then exit 1; fi
    
    - name: Download codeception
      run: wget https://codeception.com/codecept.phar
    
    - name: Run PHP development server
      run: php -S localhost:8000 &
    
    - name: Build and run codeception
      run: |
        php codecept.phar build
        php codecept.phar run --debug --fail-fast
